import { Download, LineChart } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { useDashboardContext } from '@/components/AppLayout';

const reports = [
  { name: 'Weekly dispatch summary', format: 'PDF', size: '2.8 MB', updated: '5 min ago' },
  { name: 'Yard throughput trend', format: 'CSV', size: '410 KB', updated: '11 min ago' },
  { name: 'Finance reconciliation', format: 'XLSX', size: '1.4 MB', updated: 'Today, 07:45' },
  { name: 'Aging receivables (by dealer)', format: 'CSV', size: '520 KB', updated: 'Today, 06:15' },
  { name: 'Inbound vs release SLA', format: 'PDF', size: '1.1 MB', updated: 'Yesterday' },
];

export default function ReportsPage() {
  const { dealer } = useDashboardContext();

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <p className="text-sm text-muted-foreground">Downloads & exports · {dealer}</p>
          <h1 className="text-2xl font-semibold tracking-tight text-slate-900">Reports</h1>
        </div>
        <Button>
          <Download className="mr-2 h-4 w-4" />
          Export new
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Scheduled reports</CardTitle>
          <CardDescription>Recurring exports that land in your inbox or SFTP.</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-4 md:grid-cols-3">
          {["Dispatch", "Inventory", "Finance"].map((bucket) => (
            <div key={bucket} className="space-y-2 rounded-lg border bg-muted/50 p-4">
              <div className="flex items-center gap-2 text-sm font-semibold">
                <LineChart className="h-4 w-4 text-indigo-600" />
                {bucket}
              </div>
              <Separator />
              <p className="text-sm text-muted-foreground">Runs daily at 05:00 PT</p>
              <Badge variant="secondary" className="w-fit">Active</Badge>
            </div>
          ))}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Recent exports</CardTitle>
          <CardDescription>Grab the latest exports generated by your team.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {reports.map((report) => (
            <div
              key={report.name}
              className="flex flex-col gap-2 rounded-lg border p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"
            >
              <div className="space-y-1">
                <p className="text-sm font-semibold leading-tight">{report.name}</p>
                <p className="text-sm text-muted-foreground">{report.format} · {report.size}</p>
              </div>
              <div className="flex items-center gap-3 text-sm text-muted-foreground">
                <span>{report.updated}</span>
                <Button variant="outline" size="sm" asChild>
                  <a href="#">Download</a>
                </Button>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}
